(function(g){var window=this;'use strict';var yib=function(a,b){a.gb("onAutonavCoundownStarted",b)},i5=function(a,b,c){g.zp(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.nh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.MP&&(b.lengthText?(e=b.lengthText||null,f=b.oy||null):b.lengthSeconds&&(e=g.hz(b.lengthSeconds),f=g.hz(b.lengthSeconds,!0)));var h=!!d;d=h&&g.KP(d).type==="RD";var l=b instanceof g.MP?b.isLivePlayback:null,m=b instanceof g.MP?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.LD("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Kl(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Qt};b instanceof g.LP&&(c.playlist_length=b.playlistLength);a.update(c)},j5=function(a){var b=a.U(),c=b.D;
g.U.call(this,{I:"a",S:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],va:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",
Ma:["ytp-autonav-upcoming-stamp"],va:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",va:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ma:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},k5=function(a,b){b=b===void 0?!1:b;
g.U.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.U({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.Q(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.U({I:"div",S:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],
va:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",Ma:["ytp-autonav-upcoming-stamp"],va:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});
g.Q(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Ea("ytp-autonav-endscreen-link-container"),"click",this.CV);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ea("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({I:"div",S:"ytp-autonav-overlay"});g.Q(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.U({I:"div",S:"ytp-autonav-endscreen-button-container"});g.Q(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.U({I:"button",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel auto-play"},va:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.listen("click",this.r5,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.U({I:"a",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},va:"Play now"});g.Q(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.listen("click",this.CV,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&zib(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.np(function(){Aib(c)},
500);
g.Q(this,this.D);this.BV();this.T(a,"autonavvisibility",this.BV);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.q5),this.T(a,"onAutonavCoundownStarted",this.cba))},l5=function(a){var b=a.J.xo(!0,a.J.isFullscreen());
g.zp(a.container.element,"ytp-autonav-endscreen-small-mode",a.Tg(b));g.zp(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.iN);g.zp(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Hf());g.zp(a.J.getRootNode(),"countdown-running",a.Nl());g.zp(a.container.element,"ytp-player-content",a.J.Hf());g.rm(a.overlay.element,{width:b.width+"px"});if(!a.Nl()){a.J.Hf()?Bib(a,Math.round(Cib(a)/1E3)):Bib(a);b=!!a.suggestion&&!!a.suggestion.Qt;var c=a.J.Hf()||!b;
g.zp(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.zp(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.Vx(a.B,a.J.Hf());g.zp(a.element,"ytp-enable-w2w-color-transitions",Dib(a))}},Aib=function(a){var b=Cib(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Bib(a,Math.ceil((b-c)/1E3));b-c<=500&&a.Nl()?a.select(!0):a.Nl()&&a.D.start()},Cib=function(a){if(a.J.isFullscreen()){var b;
a=(b=a.J.getVideoData())==null?void 0:b.gE;return a===-1||a===void 0?8E3:a}return a.J.pu()>=0?a.J.pu():g.IC(a.J.U().experiments,"autoplay_time")||1E4},zib=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.Q4;a.G=b==null?void 0:b.navigationEndpoint;b=b==null?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Dib=function(a){var b;
return!((b=a.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},Bib=function(a,b){b=b===void 0?-1:b;
a=a.j.Ea("ytp-autonav-endscreen-upnext-header");g.qe(a);if(b>=0){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(d>=0){a.appendChild(g.ne("Up next in $SECONDS".slice(0,d)));var e=g.me("span");g.tp(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.ve(e,b);a.appendChild(e);a.appendChild(g.ne("Up next in $SECONDS".slice(d+c.length)));return}}g.ve(a,"Up next")},m5=function(a,b){g.U.call(this,{I:"div",
Ma:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},n5=function(a){g.U.call(this,{I:"div",
Ma:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",va:"Up Next"},{I:"span",S:"ytp-upnext-title",va:"{{title}}"},{I:"span",S:"ytp-upnext-author",va:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
va:"Auto-play is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ea("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.np(this.TJ,5E3,this);this.B=0;var b=this.Ea("ytp-upnext-cancel");this.cancelButton=new g.U({I:"button",Ma:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel auto-play"},va:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.listen("click",this.s5,this);this.cancelButton.Ja(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.Q(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ea("ytp-upnext-autoplay-icon");this.T(b,"click",this.t5);this.api.createClientVe(b,this,115130);this.EV();this.T(a,"autonavvisibility",this.EV);this.T(a,"mdxnowautoplaying",this.Rba);this.T(a,"mdxautoplaycanceled",this.Sba);g.zp(this.element,"ytp-upnext-mobile",this.api.U().B)},Eib=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=(c=a.api.getVideoData())==null?void 0:c.gE;return a===-1||a===void 0?8E3:a}return a.api.pu()>=0?a.api.pu():g.IC(a.api.U().experiments,"autoplay_time")||1E4},Fib=function(a,b){b=Eib(a,b);
var c=Math,d=c.min;var e=(0,g.T)()-a.B;c=d.call(c,e,b);b=b===0?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&a.Nl()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.Nl()&&a.j.start()},o5=function(a){m5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.U({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"More videos"}]});this.N=new g.U({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new k5(this.player);g.Q(this,this.B);this.B.Ja(this.element);a.getVideoData().Yf?this.j=this.B:(this.j=new n5(a),g.PR(this.player,this.j.element,4),g.Q(this,this.j));this.overlay=new g.U({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.Q(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.WE(this);g.Q(this,this.D);g.Q(this,this.table);this.table.Ja(this.element);this.table.show();g.Q(this,this.N);this.N.Ja(this.table.element);this.hide()},p5=function(a){var b=a.Hf();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},q5=function(a,b){g.U.call(this,{I:"button",
Ma:["ytp-watch-on-youtube-button","ytp-button"],va:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.Z2();this.buttonType===2&&g.vp(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Z2);g.Vx(this,!0)},r5=function(a,b){m5.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Oe=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new q5(a,2);g.Q(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},Gib=function(a){m5.call(this,a,"subscribecard-endscreen");
this.j=new g.U({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",X:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",va:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.Q(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.VU("Subscribe",null,"Unsubscribe",null,!0,!1,b.gm,b.subscribed,"trailer-endscreen",null,a,!1);g.Q(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Ea("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ta);this.Ta();this.hide()},s5=function(a){var b=a.U(),c=g.SE||g.PO?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.U.call(this,{I:"a",Ma:e,X:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",X:c,V:[{I:"span",S:"ytp-videowall-still-info-title",va:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",va:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",va:"{{playlist_length}}"},")"]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.WE(this);g.Q(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},t5=function(a){m5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.WE(this);g.Q(this,this.B);this.K=new g.np(function(){g.vp(b.element,"ytp-show-tiles")},0);
g.Q(this,this.K);var c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},V:[g.by()]});g.Q(this,c);c.Ja(this.element);c.listen("click",this.x5,this);this.table=new g.Sx({I:"div",S:"ytp-endscreen-content"});g.Q(this,this.table);this.table.Ja(this.element);c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},V:[g.dy()]});g.Q(this,c);c.Ja(this.element);c.listen("click",this.w5,this);a.getVideoData().Yf?this.j=new k5(a,!0):this.j=
new n5(a);g.Q(this,this.j);g.PR(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},u5=function(a){return g.iS(a.player)&&a.IE()&&!a.D},v5=function(a){var b=a.Hf();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},w5=function(a){m5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new q5(a,1);g.Q(this,this.watchButton);this.watchButton.Ja(this.element);g.u8a(a)&&(this.j=new g.a1(a),g.Q(this,this.j),this.B=new g.U({I:"div",Ma:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},V:[this.j]}),g.Q(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},Kib=function(a){g.dU.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.WE(this);g.Q(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.Ps(g.$O(c))&&d&&!g.LR(a)?(this.B=!0,this.endScreen=new r5(a,g.BR(a))):a.kd()?this.endScreen=new w5(a):Hib(a)?(this.D=!0,Iib(this),this.j?this.endScreen=new o5(a):this.endScreen=new t5(a)):c.Ng?this.endScreen=new Gib(a):this.endScreen=new m5(a);g.Q(this,this.endScreen);g.PR(a,this.endScreen.element,4);Jib(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.AD("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.BD("endscreen"),function(e){b.onCueRangeExit(e)})},Iib=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.mm&&a.C===b.Yf)return!1;a.j=b.mm;a.C=b.Yf;return!0},Hib=function(a){a=a.U();
return a.yd&&!a.Ng},Jib=function(a){a.player.uf("endscreen");
var b=a.player.getVideoData();b=new g.yD(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.yD(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.qf([b,c])};
g.HR.prototype.pu=g.da(14,function(){return this.app.pu()});
g.C_.prototype.pu=g.da(13,function(){return this.getVideoData().WZ});
g.DR.prototype.Ys=g.da(12,function(a){this.Oi().Ys(a)});
g.jV.prototype.Ys=g.da(11,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.qW.prototype.Ys=g.da(10,function(a){this.overflowButton&&this.overflowButton.Ys(a)});
g.DR.prototype.Zs=g.da(9,function(a){this.Oi().Zs(a)});
g.oV.prototype.Zs=g.da(8,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.qW.prototype.Zs=g.da(7,function(a){this.shareButton&&this.shareButton.Zs(a)});
g.DR.prototype.RC=g.da(6,function(a){this.Oi().RC(a)});
g.OU.prototype.RC=g.da(5,function(a){this.fT!==a&&(this.fT=a,this.qr())});
g.DR.prototype.QC=g.da(4,function(a){this.Oi().QC(a)});
g.qW.prototype.QC=g.da(3,function(a){this.eT!==a&&(this.eT=a,this.lr())});g.z(j5,g.U);j5.prototype.select=function(){this.J.Ep(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.oF||void 0)&&this.J.logClick(this.element)};
j5.prototype.onClick=function(a){g.GS(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
j5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.z(k5,g.U);g.k=k5.prototype;g.k.bJ=function(a){this.suggestion!==a&&(this.suggestion=a,i5(this.j,a),this.playButton.updateValue("url",this.suggestion.Kl()),l5(this))};
g.k.Nl=function(){return this.C>0};
g.k.ZC=function(){this.Nl()||(this.C=Date.now(),Aib(this),yib(this.J,Cib(this)),g.zp(this.J.getRootNode(),"countdown-running",this.Nl()))};
g.k.Ry=function(){this.Xq();Aib(this);var a=this.j.Ea("ytp-autonav-endscreen-upnext-header");a&&g.ve(a,"Up next")};
g.k.Xq=function(){this.Nl()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,a===void 0?!1:a);this.Xq()};
g.k.CV=function(a){g.GS(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ea("ytp-autonav-endscreen-link-container")&&(a=this.j.Ea("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.gb("innertubeCommand",this.G),this.Xq()):this.select())};
g.k.r5=function(){this.J.logClick(this.cancelButton.element);g.JR(this.J,!0);this.cancelCommand&&this.J.gb("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&zib(this,b);var c;this.cancelCommand=(c=b.gga)==null?void 0:c.command};
g.k.cba=function(a){if(Dib(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.sz(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.sz(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.sz(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.sz(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.sz(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.sz(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.zp(this.element,"ytp-w2w-animate",!0)}};
g.k.q5=function(a){this.J.L("web_autonav_color_transition")&&a!==2&&g.zp(this.element,"ytp-w2w-animate",!1)};
g.k.BV=function(){var a=this.J.Hf();this.K&&this.Ib!==a&&g.Vx(this,a);l5(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ea("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Tg=function(a){return a.width<400||a.height<459};g.z(m5,g.U);g.k=m5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.IE=function(){return!1};
g.k.Hf=function(){return!1};
g.k.A_=function(){return!1};g.z(n5,g.U);g.k=n5.prototype;g.k.TJ=function(){this.notification&&(this.D.stop(),this.Qc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.bJ=function(a){this.suggestion=a;i5(this,a,"hqdefault.jpg")};
g.k.EV=function(){g.Vx(this,this.api.Hf());this.api.logVisibility(this.element,this.api.Hf());this.api.logVisibility(this.Ea("ytp-upnext-autoplay-icon"),this.api.Hf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Hf())};
g.k.aca=function(){window.focus();this.TJ()};
g.k.ZC=function(a){var b=this;this.Nl()||(g.Rv("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.T)(),this.j=new g.np(function(){Fib(b,a)},25),Fib(this,a),yib(this.api,Eib(this,a)));
g.xp(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Nl=function(){return!!this.j};
g.k.Ry=function(){this.Xq();this.B=(0,g.T)();Fib(this);g.vp(this.element,"ytp-upnext-autoplay-paused")};
g.k.Xq=function(){this.Nl()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=a===void 0?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.TJ(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.nh()}),this.C=this.T(this.notification,"click",this.aca),this.D.start())}this.Xq();this.api.nextVideo(!1,a)};
g.k.t5=function(a){!g.ue(this.cancelButton.element,a.target)&&g.GS(a,this.api)&&(this.api.Hf()&&this.api.logClick(this.Ea("ytp-upnext-autoplay-icon")),this.select())};
g.k.s5=function(){this.api.Hf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.JR(this.api,!0)};
g.k.Rba=function(a){this.api.getPresentingPlayerType();this.show();this.ZC(a)};
g.k.Sba=function(){this.api.getPresentingPlayerType();this.Xq();this.hide()};
g.k.xa=function(){this.Xq();this.TJ();g.U.prototype.xa.call(this)};g.z(o5,m5);g.k=o5.prototype;g.k.create=function(){m5.prototype.create.call(this);this.D.T(this.player,"appresize",this.LD);this.D.T(this.player,"onVideoAreaChange",this.LD);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.FV);this.D.T(this.player,"onAutonavCancelled",this.u5);this.onVideoDataChange()};
g.k.show=function(){m5.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.JR(this.player,!1);g.iS(this.player)&&this.IE()&&!this.C?(p5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.ZC():this.videoData.autonavState===3&&this.j.Ry()):(g.JR(this.player,!0),p5(this));this.LD()};
g.k.hide=function(){m5.prototype.hide.call(this);this.j.Ry();p5(this)};
g.k.LD=function(){var a=this.player.xo(!0,this.player.isFullscreen());p5(this);l5(this.B);g.zp(this.element,"ytp-autonav-cancelled-small-mode",this.Tg(a));g.zp(this.element,"ytp-autonav-cancelled-tiny-mode",this.rL(a));g.zp(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.rm(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.zp(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.wQ(this.videoData);b&&(this.j.bJ(b),this.j!==this.B&&this.B.bJ(b))}if(a&&a.length)for(b=0;b<Lib.length;++b){var c=Lib[b];if(a&&a[c]){this.videos[b]=new j5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,i5(d,c));g.Q(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.LD()}};
g.k.FV=function(a){a===1?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Xq(),this.Ib&&this.LD()):(this.K=!0,this.Hf()&&(a===2?this.j.ZC():a===3&&this.j.Ry()))};
g.k.u5=function(a){a?this.FV(1):(this.C=null,this.K=!1)};
g.k.IE=function(){return this.videoData.autonavState!==1};
g.k.Tg=function(a){return(a.width<910||a.height<459)&&!this.rL(a)&&!(a.width<=400||a.height<=360)};
g.k.rL=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.k.Hf=function(){return this.Ib&&g.iS(this.player)&&this.IE()&&!this.C};
var Lib=[1,3,2,4];g.z(q5,g.U);g.k=q5.prototype;g.k.Z2=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.HS(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.RO(b)){var c={};g.RO(b)&&g.rR(this.J,"addEmbedsConversionTrackingParams",[c]);if(!this.J.L("embeds_web_enable_referring_feature_deprecation")){a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.gL(c,b)}a=g.aj(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Ib&&this.Z)};
g.k.show=function(){g.U.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.U.prototype.hide.call(this);this.logVisibility()};
g.k.Nc=function(a){g.U.prototype.Nc.call(this,a);this.logVisibility()};g.z(r5,m5);r5.prototype.show=function(){this.player.getPlayerState()!==3&&(m5.prototype.show.call(this),this.Oe.QC(!0),this.Oe.Zs(!0),this.J.U().mf||this.Oe.Ys(!0),this.J.logVisibility(this.element,!0),this.watchButton.Nc(!0))};
r5.prototype.hide=function(){m5.prototype.hide.call(this);this.Oe.QC(!1);this.Oe.Zs(!1);this.Oe.Ys(!1);this.J.logVisibility(this.element,!1);this.watchButton.Nc(!1)};g.z(Gib,m5);Gib.prototype.Ta=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.gm;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.z(s5,g.U);s5.prototype.select=function(){this.api.Ep(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.oF||void 0)&&this.api.logClick(this.element)};
s5.prototype.onClick=function(a){if(g.RO(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Kl(),c={};g.MR(this.api,c,"emb_rel_end");b=g.aj(b,c);g.HS(b,this.api,a)}else g.GS(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
s5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
s5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Jf?!1:b.D};g.z(t5,m5);g.k=t5.prototype;g.k.create=function(){m5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.yr();this.B.T(this.player,"appresize",this.yr);this.B.T(this.player,"onVideoAreaChange",this.yr);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.NN);this.B.T(this.player,"onAutonavCancelled",this.v5);a=this.videoData.autonavState;a!==this.Y&&this.NN(a);this.B.T(this.element,"transitionend",this.oda)};
g.k.destroy=function(){g.it(this.B);g.ib(this.stills);this.stills=[];m5.prototype.destroy.call(this);g.xp(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.IE=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var a=this.Ib;m5.prototype.show.call(this);g.xp(this.element,"ytp-show-tiles");this.player.U().B?g.pp(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.JR(this.player,!1);u5(this)?(v5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.ZC():this.videoData.autonavState===3&&this.j.Ry()):(g.JR(this.player,!0),v5(this));a!==this.Ib&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Ib;m5.prototype.hide.call(this);this.j.Ry();v5(this);a!==this.Ib&&this.player.logVisibility(this.element,!1)};
g.k.oda=function(a){a.target===this.element&&this.yr()};
g.k.yr=function(){var a,b,c,d;var e=((a=this.videoData)==null?0:(b=a.suggestions)==null?0:b.length)?(c=this.videoData)==null?void 0:c.suggestions:[(d=this.videoData)==null?void 0:g.wQ(d)];if(e.length){g.vp(this.element,"ytp-endscreen-paginate");var f=this.J.xo(!0,this.J.isFullscreen());if(a=g.BR(this.J))a=a.Nh()?48:32,f.width-=a*2;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;p>0&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,u=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&u)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(u)p-=q*n,b+=2;else break}d=!1;p>=3*n&&c*n-p<=6&&(b>=4||a>=4)&&(d=!0);n=a*96;p=b*54;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Hm(f,n,p);g.rm(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.bJ(g.wQ(this.videoData));this.j instanceof
k5&&l5(this.j);g.zp(this.element,"ytp-endscreen-takeover",u5(this));v5(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:m%2===0&&l%2===0&&(m<2&&l<2?m===0&&l===0&&(t=2):t=2),q=g.Id(q+this.C,c),t!==0){r=this.stills[h];r||(r=new s5(this.player),this.stills[h]=r,f.appendChild(r.element));u=Math.floor(p*m/b);var x=Math.floor(n*l/a),A=Math.floor(p*(m+t)/b)-u-4,C=Math.floor(n*(l+t)/a)-x-4;g.Dm(r.element,x,u);g.Hm(r.element,C,A);g.rm(r.element,"transitionDelay",
(m+l)/20+"s");g.zp(r.element,"ytp-videowall-still-mini",t===1);g.zp(r.element,"ytp-videowall-still-large",t>2);t=Math.max(C,A);g.zp(r.element,"ytp-videowall-still-round-large",t>=256);g.zp(r.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.zp(r.element,"ytp-videowall-still-round-small",t<=96);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.up(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",i5(r,q,u),g.RO(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Kl(),u={},g.rR(r.api,"addEmbedsConversionTrackingParams",[u]),r.api.L("embeds_web_enable_referring_feature_deprecation")||g.gL(u,"emb_rel_end"),t=g.aj(t,u),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.zp(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.se(a.element),g.gb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.wQ(a)?(this.C=0,this.videoData=a,this.yr()):this.player.oa("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.k.w5=function(){this.C+=this.stills.length;this.yr()};
g.k.x5=function(){this.C-=this.stills.length;this.yr()};
g.k.A_=function(){return this.j.Nl()};
g.k.NN=function(a){a===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Xq(),this.Ib&&this.yr()):(this.G=!0,this.Ib&&u5(this)&&(a===2?this.j.ZC():a===3&&this.j.Ry()))};
g.k.v5=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.NN(1)}else this.D=null,this.G=!1;this.yr()};
g.k.Hf=function(){return this.Ib&&u5(this)};g.z(w5,m5);w5.prototype.show=function(){if(this.player.getPlayerState()!==3){m5.prototype.show.call(this);var a=this.B;if(a){var b=this.j.suggestionData.length>0;g.zp(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;(c=g.BR(this.player))==null||c.RC(!0);this.player.logVisibility(this.element,!0);this.watchButton.Nc(!0)}};
w5.prototype.hide=function(){m5.prototype.hide.call(this);var a;(a=g.BR(this.player))==null||a.RC(!1);this.player.logVisibility(this.element,!1);this.watchButton.Nc(!1)};g.z(Kib,g.dU);g.k=Kib.prototype;g.k.Mv=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.kd()||this.B)&&!b)return!0;var c;var d=!!((a==null?0:g.wQ(a))||(a==null?0:(c=a.suggestions)==null?0:c.length));d=!Hib(this.player)||d;a=a.dk;c=this.player.CF();return d&&!a&&!c&&!b};
g.k.Hf=function(){return this.endScreen.Hf()};
g.k.N$=function(){return this.Hf()?this.endScreen.A_():!1};
g.k.xa=function(){this.player.uf("endscreen");g.dU.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Bb().Je.get("heartbeat"),d=g.wQ(a);!d||b.videoId!==d.videoId||a.ZW?(this.player.Ep(b.videoId,void 0,void 0,!0,!0,b),c&&c.yL("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.dU.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.dU.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Mv()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Jib(this);this.D&&Iib(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new o5(this.player):this.endScreen=new t5(this.player),g.Q(this,this.endScreen),g.PR(this.player,this.endScreen.element,4))};g.cU("endscreen",Kib);})(_yt_player);
